### PR TITLE
Docs: Type mismatch explanation for dynamic imports with TS

### PR DESCRIPTION
**Pull request by charlieforward9**
Originally planned to put the explanation outside of the code, but preferred to leave it as a comment to avoid 'not-seeing the notice' discussions from showing up in the future.

### CODE REVIEW

**Comment by charlieforward9** [comment]
Addressing #693

**Comment by brillout** [comment]
Thanks! Also thanks for the sponsoring 💚.

**Comment by charlieforward9** [comment]
Thanks for providing great software and support!

**Comment by brillout** [comment]
I'm glad you like it!

**Pull request merged**
