### PR TITLE
docs(example): Add Clerk integration

### PR DESCRIPTION
**Pull request by wobsoriano**
https://github.com/brillout/vite-plugin-ssr/assets/13049130/9d7e00ab-40f1-4c58-a74f-6cf8f7e4227d

### CODE REVIEW

**Comment by brillout** [comment]
Very neat 💯.

Have you seen the brand new `examples/auth/` featuring [`guard()`](https://vite-plugin-ssr.com/guard) and [throw render()](https://vite-plugin-ssr.com/render)? There is also [`throw redirect()`](https://vite-plugin-ssr.com/redirect).

**Comment by wobsoriano** [comment]
> Very neat 💯.
> 
> Have you seen the brand new `examples/auth/` featuring [`guard()`](https://vite-plugin-ssr.com/guard) and [throw render()](https://vite-plugin-ssr.com/render)? There is also [`throw redirect()`](https://vite-plugin-ssr.com/redirect).

I haven't checked yet and that already looks like some sick new VPS features I need to integrate to the example!

**Comment by brillout** [comment]
Yea these are quite neat... although it has to be seen whether Clerk offers low-level enough primivites to leverage `guard()` and `throw render()`/`throw redirect()`. Worst case we can do it the old-school way.

**Comment by brillout** [comment]
Closing, but we can still continue working on it: I'll re-open when it's ready for review. Looking forward to it.

**Pull request closed without merging**
