### PR TITLE
refactor: use fs promises interface in prerender.ts

### PR DESCRIPTION
**Pull request by gryphonmyers**
Node provides built-in promise interfaces for fs functions, so wrapping the cb versions is unnecessary

### CODE REVIEW

**Comment by brillout** [comment]
As much as I would love this, `fs/promises` is unfortunately only available in late Node.js versions. Node 14 IIRC.

**Comment by gryphonmyers** [comment]
Good catch - I switched to the slightly older fs.promises interface, which should be available in Node 12 https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_fs_promises_api

**Comment by brillout** [comment]
Neat, didn't know about these.

> This branch cannot be rebased due to conflicts

I'll merge once the conflicts resolved.

**Comment by brillout** [comment]
Any luck if the merge conflict? I can do it if you want

**Comment by gryphonmyers** [comment]
I haven't looked yet. I did resolve merge conflicts before and I currently see this as green / ok to merge in GitHub, so I'm not 100% sure what's up. Maybe because you're doing a rebase not a merge?

**Comment by brillout** [comment]
👍 I guess the squash part did it.

**Pull request merged**
