### PR TITLE
Add eslint to react boilerplates.

### LINKED ISSUE #804: Add ESLint to React boilerplates
### Description

https://github.com/vitejs/vite/pull/12801

### PR DESCRIPTION
**Pull request by Abhirup-99**
Fixes #804.

### CODE REVIEW

**Comment by brillout** [comment]
Neat 👌 

LGTM. Although I wonder:
 - In [Vite's PR](https://github.com/vitejs/vite/pull/12801/files#diff-5fab9ae1cca0fb720e321a07982182c09b5189274b487dcafe552d39317febcdR10), they added `settings`. Thoughts on this? Is omitting `settings` equivalent to `settings: { react: { version: 'detect' } }`?
 - Why omtting `plugin:react/jsx-runtime` for the TS boilerplate?
 - Can the options of `"lint": "eslint src --ext js,jsx --report-unused-disable-directives --max-warnings 0"` be set in `.eslintrc.cjs`? Would be neat to only have `"lint": "eslint"`.

Good idea of adding `prop-types` for the JS boilerplate. FYI I went ahead and made some minor improvements. Notable change:
 - I added `npm run lint` to the `prod` npm script. Let me know if you see problems with that. The idea here is to ensure that linting is green when running the CI (of VPS and perspectively the app's CI).

**Comment by brillout** [comment]
👍 And any thoughts about https://github.com/brillout/vite-plugin-ssr/pull/837#issuecomment-1531031936?

**Comment by rtritto** [comment]
> * In [Vite's PR](https://github.com/vitejs/vite/pull/12801/files#diff-5fab9ae1cca0fb720e321a07982182c09b5189274b487dcafe552d39317febcdR10), they added `settings`. Thoughts on this? Is omitting `settings` equivalent to `settings: { react: { version: 'detect' } }`?

Idk if it's equivalent, so it's safe to use `detect`.

> * Why omtting `plugin:react/jsx-runtime` for the TS boilerplate?

It needs to be added.

> * Can the options of `"lint": "eslint src --ext js,jsx --report-unused-disable-directives --max-warnings 0"` be set in `.eslintrc.cjs`? Would be neat to only have `"lint": "eslint"`.

Yes, I will change script to `"lint": "eslint ."` and move the script options to `eslintrc` file.

**Comment by brillout** [comment]
> Yes, script should be changed to `"lint": "eslint ."` and move the script options to `eslintrc` file.

👍

@Abhirup-99 Up for finish the PR? Let me know if you're busy and I'll finish it.

**Pull request merged**
