### PR TITLE
feat(types): Export SanitizedHtmlString

### PR DESCRIPTION
**Pull request by CanRau**
This allows to properly type `render` function in `.server.tsx` files

Or is there other ways? I'm still kinda newish to Typescript 😬

### CODE REVIEW

**Comment by CanRau** [comment]
Cause my ESLint is complaining 😅
```
Missing return type on function. eslint(@typescript-eslint/explicit-module-boundary-types)
```

**Comment by brillout** [comment]
I see three options:
1. Change your ESlint
2. Set return to `any` (if ESlint allows you...)
3. We make a proper PR out of this, including digging into `declare module`

:)

**Comment by CanRau** [comment]
Yea, I'd love to help with 3. but I'm afraid my Typescript skills won't
suffice 😬

Keeping it at `any` for now then.

Maybe I feel more explorative some other day if still needed 🤞

Thanks a lot for this fantastic plugin 🙌

Romuald Brillout ***@***.***> schrieb am Do., 5. Aug. 2021,
02:48:

**Comment by brillout** [comment]
Sounds good 👍

**Comment by brillout** [comment]
Closing this in the meantime. Let's reopen later.

**Pull request closed without merging**
