### PR TITLE
Update styled-components.page.server.mdx

### PR DESCRIPTION
**Pull request by alexrabin**
Added more indepth guide for styled components

### CODE REVIEW

**Comment by brillout** [comment]
Hi Alex, thanks for the PR!

I'm thinking: how about a community example at `github.com/alexrabin` showcasing VPS + styled-components?

**Comment by alexrabin** [comment]
@brillout I personally would prefer this example to be in the documentation. When I was trying to figure out how to add styles components I would have loved to have been able to find an example in the documentation as I would imagine other developers would as well.

**Comment by brillout** [comment]
I think https://styled-components.com/docs/advanced#server-side-rendering does already a great job at that, so I think the added value wouln't be worth the added maintainability burden.

An example would be quite lovely though, I think.

**Comment by brillout** [comment]
We can point the docs towards the "interesting bits" of the example, I think that would work equally well if not better.

**Comment by alexrabin** [comment]
Maybe I can add to the vite-plugin-ssr examples folder with react and styled components and then we can link that example in the docs?

**Comment by brillout** [comment]
The `examples/` folder is getting quite big and hard to maintain. That's why I'm leaning towards have the example live somewhere else.

**Comment by alexrabin** [comment]
Well the goal is for a developer to come across the styles components page and easily know how to implement it with vite ssr, so if I created my own example, would we add a link to that example in the documentation?

**Comment by brillout** [comment]
Yes, that's what I was thinking so far.

**Comment by alexrabin** [comment]
Okay, I'll get to work on that later today and then can update this pr accordingly

**Comment by alexrabin** [comment]
@brillout I'm working on creating an article tutorial on adding styled-components to VPS. Is it okay if I add that into this document?

**Comment by alexrabin** [comment]
@brillout  I updated the branch with the example project and a link to the tutorial

**Comment by brillout** [comment]
Wonderful 💚, and neat blog post! Feel free to ping me on Discord and I'll add you to Cubes's contributor list.

**Comment by alexrabin** [comment]
Fantastic. I'll ping you

**Pull request merged**
