### PR TITLE
Readme: Add URL to comparison with NextJS

### PR DESCRIPTION
**Pull request by redbar0n**
Since it's useful documentation,  and was requested in https://github.com/brillout/vite-plugin-ssr/issues/158#issuecomment-1345461730

### CODE REVIEW

**Comment by brillout** [comment]
While I share the sentiment here, I'm reluctant to do this out for marketing style.

Thanks for the PR nevertheless.

**Comment by redbar0n** [comment]
hmm.. what do you mean by «out for marketing style»?

**Comment by redbar0n** [comment]
See similar pages:

https://tanstack.com/query/v4/docs/comparison

https://formidable.com/open-source/urql/docs/comparison/

**Comment by brillout** [comment]
After [VPS's new design](https://github.com/brillout/vite-plugin-ssr/issues/53) (which includes Nested Layouts) we can rename the section "Full-fledged" on `https://vite-plugin-ssr.com/` to "Feature-complete" and mention complete Next.js feature coverage.

Under "Overview" we can add a "Migrate from Next.js" title.

Since the new design will mark the v1 release, we can then rename the "Rock-solid" section to "Stable".

I foresee the v1 to live quite a long time.

But, most importantly, the big sellers are going to be the frameworks built on top of VPS. Including one I'm currently building. The second, and even bigger seller, will be Stem.

**Comment by redbar0n** [comment]
Yes, but a [comparison table](https://github.com/brillout/vite-plugin-ssr/issues/158#issuecomment-1250068578) detailing every feature, even those that vite-plugin-ssr has and NextJS doesn't have, is still valuable, imho..

**Comment by brillout** [comment]
Ok. But then I'd say let's add it to `https://vite-plugin-ssr.com`. How about a new page under "Overview"?

**Comment by redbar0n** [comment]
Awesome! That sounds like a good idea. I suggest calling it "NextJS comparison".

Created a PR: https://github.com/brillout/vite-plugin-ssr/pull/559

**Pull request closed without merging**
