### PR TITLE
Add example for Cloudflare Workers with esbuild

### PR DESCRIPTION
**Pull request by dan-lee**
This is a follow-up PR for the suggestion https://github.com/brillout/vite-plugin-ssr/issues/267#issuecomment-1068839627.

I also added some explanations in the docs. Feel free to edit, remove, or whatever :)

### CODE REVIEW

**Comment by brillout** [comment]
Regression tests for Cloudflare Workers + esbuild integration added :-).

**Comment by brillout** [comment]
```
[08:38:33.339][stderr][/examples/cloudflare-workers-esbuild][npm run preview:wrangler] Error: missing field `upload`
```
From https://github.com/brillout/vite-plugin-ssr/runs/5582827133?check_suite_focus=true#step:8:86.

Ideas what's going on? Note that it's working for `/examples/cloudflare-workers/`.

**Comment by dan-lee** [comment]
Looks like it's missing `[build.upload` section. Don't know why it's working for the other example though.
Can you try adding the following to `wrangler.toml`?

```
[build.upload]
format = "service-worker"
main = "./worker.js"
```

(or `format = "module"` if it's ESM, can't remember which it was.)

**Comment by brillout** [comment]
With `format = "module"`:

```
🌀  Running yarn build:worker
yarn run v1.22.17
warning package.json: No license field
$ node ./build-worker.js
Worker built successfully
Done in 0.75s.
🌀  Created namespace for Workers Site "__vite-plugin-ssr_worker-example-workers_sites_assets_preview"
✨  Success
Error: Something went wrong with the request to Cloudflare...
Uncaught SyntaxError: Unexpected token 'export'
  at line 1
 [API code: 10021]
 ELIFECYCLE  Command failed with exit code 1.
```

With `format = "service-worker"`:

```
Error: unknown field `main`, there are no fields
 ELIFECYCLE  Command failed with exit code 1.
```

The `wrangler.toml`:

```
[build.upload]
format = "service-worker"
main = "./worker.js"
```

If I remove `main` I get ``Error: Your JavaScript project is missing a `package.json` file; is `/home/romuuu/.prog/files/code/vite-plugin-ssr/examples/cloudflare-workers-esbuild/./worker` the wrong directory?``.

**Comment by dan-lee** [comment]
Ok, I got it running. Add this to `package.json`:

```
  "main": "dist/worker.js",
```

And the `build.upload` section has to be only:

```
[build.upload]
format = "service-worker"
```

Don't ask me why this is 😅 I've used it with `format = "module"` and a `main` field in the `wrangler.toml` in my production project.

**Comment by brillout** [comment]
I still get ``Error: Your JavaScript project is missing a `package.json` file; is `/home/romuuu/.prog/files/code/vite-plugin-ssr/examples/cloudflare-workers-esbuild/./worker` the wrong directory?``.

```
~/code/vite-plugin-ssr/examples/cloudflare-workers-esbuild (master% u+1) head package.json 
{
  "type": "module",
  "main": "dist/worker.js",
  "scripts": {
    "// Development server": "",
    "dev": "node ./dev-server",
    "// Preview worker locally": "",
    "preview": "npm run preview:miniflare",
    "preview:miniflare": "npm run build:vite && miniflare --port 3000 dist/worker.js",
    "preview:wrangler": "npm run build:vite && wrangler dev --port 3000",
```

```
~/code/vite-plugin-ssr/examples/cloudflare-workers-esbuild (master% u+1) cat wrangler.toml 
name = "vite-plugin-ssr_worker-example"
compatibility_date = "2021-09-29"
account_id = ""
workers_dev = true
type = "javascript"

[build]
command = "yarn build:worker"
[build.upload]
format = "service-worker"

[site]
bucket = "./dist/client"
entry-point = "./worker"
```

**Comment by dan-lee** [comment]
Oof, I didn't try it with an `account_id` and it failed afterward.
It looks like the `[site]` section is the reason.

With this config it goes through:
```
[site]
bucket = "./dist/client"
entry-point = "."
```

> 🌀  Running yarn build:worker
warning package.json: No license field
$ node ./build-worker.js
Worker built successfully
🌀  Using namespace for Workers Site "__vite-plugin-ssr_worker-example-workers_sites_assets_preview"
✨  Success
👂  Listening on http://127.0.0.1:3000

**Comment by brillout** [comment]
Yep, works now 👌.

**Pull request merged**
