### PR TITLE
fix: fixes build process on Windows

### LINKED ISSUE #74: `npm run build` fails on windows
### Describe the bug
`npm run build` fails on Windows systems

### Steps to reproduce

On a windows based system

```cmd
git clone git@github.com:brillout/vite-plugin-ssr.git vite-plugin-ssr
cd vite-plugin-ssr
npm install
npm run build
```

### Expected result
`vite-plugin-ssr` builds without errors

### Actual result

```cmd

> build
> npm run clean:build && npm run tsc:once


> clean:build
> rm -rf src/dist/

'rm' is not recognized as an internal or external command,
operable program or batch file.
```

### Other comments
~~A PR fixing the issue will be provided~~

#75 provides a fix similar to what `vite` uses

### PR DESCRIPTION
**Pull request by ferdinando-ferreira**
This PR replaces `rm -rf` with rimraf to ensure it works properly on Windows (in the same way it is done on `vite` and other packages).

Fixes #74

### CODE REVIEW

**Comment by brillout** [comment]
Neat 👍 .

One little thing: the user should still be able to follow the steps of https://github.com/brillout/vite-plugin-ssr/tree/master/examples/react. We should also add the rimraf dependency to each example.

**Comment by ferdinando-ferreira** [comment]
> We should also add the rimraf dependency to each example.

It was added to every instance of "rm -rf", including that one.

**Comment by brillout** [comment]
Thanks 👍

**Comment by brillout** [comment]
FYI https://github.com/brillout/vite-plugin-ssr/commit/d12ca50412a83f5011af545184ebf3ca52df9275 :-)

**Comment by ferdinando-ferreira** [comment]
Thanks, I was unaware of the best way to add the dependency.

**Pull request merged**
