### PR TITLE
React + TypeScript + Fastify boilerplate

### PR DESCRIPTION
**Pull request by giacomorebonato**
Hi, thanks a lot for this plugin. I think it's great!

I enjoy using Fastify instead of Express and I thought it could have been a nice idea to have a boilerplate for that too.

### CODE REVIEW

**Comment by giacomorebonato** [comment]
I can't figure out what's breaking the test on Win Node 14

**Comment by brillout** [comment]
Nice! A lot of folks have been asking for a fastify example.

Although: I'd rather move the example to your GitHub handle and add links to it in VPS's docs.

**Comment by giacomorebonato** [comment]
May I ask you why you think that it's not a good idea to include the Fastify example?

I thought it was handy to be listed in the CLI options for scaffolding a new project.

**Comment by brillout** [comment]
Because of feature creep.

**Comment by brillout** [comment]
@giacomorebonato Up for moving the example to your GitHub handle? I'll then add links to it in the docs.

**Comment by giacomorebonato** [comment]
Forgive me, but I don't know what it means to:
> Up for moving the example to your GitHub handle

Does it mean that I merge it on main on my fork?

**Comment by brillout** [comment]
I meant to move your example to `https://github.com/giacomorebonato/vite-plugin-ssr_fastify`. I'll then create a Fastify page `https://vite-plugin-ssr.com/fastify` and add your example to it.

**Comment by giacomorebonato** [comment]
I will 👍

**Comment by giacomorebonato** [comment]
Created: https://github.com/giacomorebonato/vite-plugin-ssr-fastify

**Comment by brillout** [comment]
Wonderful. Added to docs 10694b37822575919dd37ee85a82754f3a612081.

**Pull request closed without merging**
