### PR TITLE
perf: stop using `new URL()`

### PR DESCRIPTION
**Pull request by brillout**
@dajinchu What's the after/before benchmark for this PR? 👀

Looking forward to get to the bottom of https://github.com/brillout/vite-plugin-ssr/issues/1115.

### CODE REVIEW

**Comment by dajinchu** [comment]
```
main (dce0fcbf853d6e2928dd15fdf81d4e31448dbb31)
Statistics        Avg      Stdev        Max
  Reqs/sec      2272.30    1333.74    8561.49
  Latency       54.91ms    76.17ms   580.20ms

faster-new-url
Statistics        Avg      Stdev        Max
  Reqs/sec      2404.49    1427.65   12806.86
  Latency       51.99ms    72.33ms   563.25ms

0.4.141 (36fb43a3cf593048ba0812a2728f04ad24bd0048)
Statistics        Avg      Stdev        Max
  Reqs/sec      1244.47     854.00   12205.80
  Latency      100.83ms   138.14ms   848.28ms
```

**Comment by brillout** [comment]
That's weird.

**Comment by brillout** [comment]
I just double checked f1b34b04c514d215d2102d280f0689331f95f168 and I really can't see how the try-catch can cause performance issues.

**Comment by dajinchu** [comment]
Prior benchmarks are run with 125 concurrent connections which increases latency and hides how small the orders of magnitude we're dealing with. Running just 1 connection paints a clearer picture:
```
faster-new-url
Statistics        Avg      Stdev        Max
  Reqs/sec      2378.05     466.67    3158.04
  Latency      418.90us   615.61us    20.46ms

0.4.141 (36fb43a3cf593048ba0812a2728f04ad24bd0048)
Statistics        Avg      Stdev        Max
  Reqs/sec      1296.02     225.05    1858.76
  Latency      770.36us     1.25ms    76.21ms
```

At the microsecond scale, error handling does add some overhead. if we're calling `parseUrl` 40 times/request, each error adding `10us` would account for this difference.

flamegraph on `36fb43a3cf593048ba0812a2728f04ad24bd0048` shows:
image

**Comment by brillout** [comment]
Thanks for the insightful digging & information.

I'm still merging the changes as the custom implementation is cleaner and gives us complete control; it's neat that we're getting rid of the `new URL()` workarounds.

> As an aside, the fact that all the routing and rendering (for a basic page) is running in < 1ms is pretty sweet. I just happen to care a lot about overhead due to our proxying use case.

I'm glad it works out for you 👍. (Also let me know if you hit issues with `cumulative`.)

**Pull request merged**
