### PR TITLE
add pm2 example

### PR DESCRIPTION
**Pull request by hemengke1997**
Maybe some developer use pm2 to deploy website.
Here is my usecase. I've tested in local.

BTW, I have a question: 

why vps add `extractStyles` suffix to some file ?

At last , I want to say , the source code of vps is great. Thank you very much !!

### CODE REVIEW

**Comment by brillout** [comment]
👍.

How about we move it in a repository under your name `hemengke1997` and add a link to it at https://github.com/brillout/vite-plugin-ssr/tree/main/examples#community-examples?

> why vps add `extractStyles` suffix to some file ?

https://vite-plugin-ssr.com/includeAssetsImportedByServer

**Comment by brillout** [comment]
Let me know when it's ready then I'll add it to the community examples. Or feel free to PR the community section.

**Comment by hemengke1997** [comment]
Here is the repo link: https://github.com/hemengke1997/vite-plugin-ssr-pm2

**Comment by brillout** [comment]
Added 💯. Thanks!

**Pull request closed without merging**
