### PR TITLE
Replace node path with pathe library

### PR DESCRIPTION
**Pull request by kochrt**
Haven't run tests yet

### CODE REVIEW

**Comment by kochrt** [comment]
#445

**Comment by brillout** [comment]
Tests are passing, including the [wrangler ones](https://github.com/brillout/vite-plugin-ssr/commits/tmp-remove-path) 🎉.

Maybe we can use a little custom implementation instead of `pathe`? So far, it seems me so that it's doable with only a couple lines of code. Especially given that we can assume paths to be posix (Vite normalizes the paths).

**Comment by kochrt** [comment]
After pushing a minimal implementation I see you say vite normalizes the path. Does this mean we don't need the `normalize` method? We can just assume it's all normalized? That would help because I was about to say I've pulled in like half of the `pathe` library into this shim

**Comment by brillout** [comment]
Yes, Vite does some normalization already. I didn't take a close look at it but seems like we don't need most of it?

If we do then, yea, we might as well just use `pathe` then 😄.

**Comment by kochrt** [comment]
If it were up to me I would just go with `pathe`, it's small, doesn't have any dependencies of its own, and I trust it more than a shim that I'm picking and choosing to implement. Maybe make a follow up bug to pull out only the bare minimum from `pathe`.

If I knew more about what vite does and doesn't normalize, or wasn't just error-chasing in this PR, I might be more confident in my shim.

**Comment by brillout** [comment]
Released as `0.4.112`.

FYI: the shim ended being a one-liner. We saved ourself an extra dependency 🙂.

Thanks for the PR. It was fun.

**Pull request merged**
