### PR TITLE
adding miniflare and tests to cloudflare workers examples

### PR DESCRIPTION
**Pull request by rslonik**

### CODE REVIEW

**Comment by rslonik** [comment]
I went to check what @lukeed was using (he always build a lot of cool stuff) and he wrote one test runner 😅 https://github.com/lukeed/uvu

**Comment by brillout** [comment]
Yea I know about `uvu` but it still doesn't quite nail it. But yea I'll re-consider uvu, let's see if it changed since the last time I checked it out.

**Comment by brillout** [comment]
Got it working, but `wrangler` doesn't work in GitHub actions because:

> Please run `wrangler login`, `wrangler config`

Is there a way to use `wrangler` in GitHub actions?

**Comment by rslonik** [comment]
Yes, I have a project that uses this to upload static generated site to workers. The step in my action is this:

```
- uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        environment: 'development'
        wranglerVersion: '1.18.0'
```

**Comment by brillout** [comment]
And `${{ secrets.CF_API_TOKEN }}` can be hidden even for public GitHub repos?

**Comment by rslonik** [comment]
Secrets are set in repo's settings > secrets. I think it's safe.

https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by brillout** [comment]
Ah, I actually just stumbled about this page :-) Thanks

**Comment by brillout** [comment]
Both `miniflare` and `wrangler` are now included in the test suite.

**Pull request merged**
