### PR TITLE
docs: Add WindiCSS Guide to Readme

### PR DESCRIPTION
**Pull request by CanRau**
As requested in https://github.com/brillout/vite-plugin-ssr/issues/36#issuecomment-818017489

Let me know if that works for you.

Could provide a basic example soonish, but don't count on that as I'm a little distracted from offline things at the moment 🤪

### CODE REVIEW

**Comment by brillout** [comment]
Wonderful 👌 ❤️

**Comment by brillout** [comment]
> Could provide a basic example soonish, but don't count on that as I'm a little distracted from offline things at the moment 🤪

No worries :-)

**Comment by CanRau** [comment]
Just stumbled upon an alternative to `windi.config.js` directly in `vite.config.js` should I include that, too? @brillout (not sure how notifications work on merged PRs 🤔)

**Comment by brillout** [comment]
Yes even better then

**Comment by brillout** [comment]
> not sure how notifications work on merged PRs 🤔)
GH always notifies

**Pull request merged**
