### PR TITLE
Fixes to Vue examples

### PR DESCRIPTION
**Pull request by AurelienLourot**
(See commit messages for more details)

### CODE REVIEW

**Comment by AurelienLourot** [comment]
@brillout do you have mismatching `module` and `moduleResolution` on purpose in https://github.com/brillout/vite-plugin-ssr/blob/main/vite-plugin-ssr/tsconfig.json ?

```
$ pnpm run build

> vite-plugin-ssr@0.4.139 build /home/lourot/Documents/git/vike/vite-plugin-ssr/vite-plugin-ssr
> rimraf dist/ && pnpm run build:esm && pnpm run build:cjs


> vite-plugin-ssr@0.4.139 build:esm /home/lourot/Documents/git/vike/vite-plugin-ssr/vite-plugin-ssr
> tsc

tsconfig.json:6:15 - error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.

6     "module": "ES2020",
                ~~~~~~~~


Found 1 error in tsconfig.json:6

 ELIFECYCLE  Command failed with exit code 2.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by brillout** [comment]
Last time I tried to update `vite-plugin-md` to its latest version it had some bug. It didn't seem related to vite-plugin-ssr so that's why I just keep using its `0.11.x` release branch.

As for TypeScript: I don't get this error on a fresh install/build `$ pnpm reset` which installs TypeScript `5.1.6`. Maybe you had another TypeScript version installed.

**Comment by AurelienLourot** [comment]
Thanks for your answer. I'm confused because what I was trying to fix in the first place is that `vite-plugin-md@0.11.9` has a peer dependency to `vite@"^2.0.0"` and we have a peer dependency to `vite@"^4.4.8"`, and this led to a clash on my setup at some point, on `main`. I'll try to reproduce.

**Comment by brillout** [comment]
Such peer dependency is basically just a recommendation; it may *or may not* break things if you don't respect it.

Since the CI was green, I guess ignoring it didn't break things so far; the markdown page is part of the CI. Maybe you bumped some dependencies and things started to break.

**Comment by AurelienLourot** [comment]
@brillout if you follow the readme of the `vue-full-v1` example, i.e. you use `npm` and not `pnpm` you can reproduce the issue:

```
$ git clone git@github.com:brillout/vite-plugin-ssr
$ cd vite-plugin-ssr/
$ git checkout main
$ pnpm clean
$ cd examples/vue-full-v1/
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vite@4.4.9
npm ERR! node_modules/vite
npm ERR!   vite@"^4.4.8" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.0" from vite-plugin-md@0.11.9
npm ERR! node_modules/vite-plugin-md
npm ERR!   vite-plugin-md@"^0.11.8" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by AurelienLourot** [comment]
So I intend to find a way to have a newer version of `vite-plugin-md` with which we don't have a peer dependency version clash, and at the same time fix the Vue tests that are failing now on CI. What do you think?

**Comment by brillout** [comment]
That'd be nice yes. Otherwise, if we do need a fix from `vite-plugin-md` and we're blocked by it, then we could set [`legacy-peer-deps`](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps) in `examples/vue-full-v1/.npmrc`.

**Comment by AurelienLourot** [comment]
I can reproduce the `pnpm run test:types` failure locally. I'll have a look.

**Comment by brillout** [comment]
The failing React test is a flaky test (I couldn't find a way to make it stable). I've added you as collaborator so that you can re-run the CI. Once we do the Vike rename, you'll have full privileges.

**Comment by brillout** [comment]
I just found the bug report: https://github.com/antfu/vite-plugin-md/issues/112. This means that its `0.22.x` release branch may work. That's neat as it gives users the choice between two (fairly) well maintained markdown plugins. I'll update the docs accordingly.

**Comment by AurelienLourot** [comment]
Thanks! I'm happy with the PR now. Do you want me to give a try at `vite-plugin-md@0.22` or are we fine with how it is now?

**Comment by brillout** [comment]
We can let the users try (they'll surely/eventually report back if there is an issue with it), or we can preemptively check on behalf of users. The lazy path seems fine to me, but as you wish :-).

Neat polishing PR 👌.

**Comment by brillout** [comment]
> tsconfig.json:6:15 - error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.

[Fixed](https://github.com/brillout/vite-plugin-ssr/commit/c124c6b9bf3e7fb2e29fc4d829bd1d297f15ef94).

FYI ths issue was that TypeScript 5.2 [made a breaking change about this](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#module-and-moduleresolution-must-match-under-recent-node-js-settings).

It seems like you were using a TS version that wasn't the one specified by `pnpm-lock.yaml`. (Maybe VSCode doesn't use the tsserver of the local TypeScript installation.)

**Pull request merged**
