### PR TITLE
chore!: update to Node.js 20

### PR DESCRIPTION
**Pull request by rtritto**
### Changes:
- updated `pnpm` version from _7.9.5_ to _8.4.0_
- added Node.js v20 (release date: _18 Apr 2023_)
- removed Node.js v14 (EOL: _30 Apr 2023_)
- in `package.json` of `vite-plugin-ssr`
  - locked minor _dependency_ versions
  - updated _@types/node_ to v20

### CODE REVIEW

**Comment by brillout** [comment]
Does it bring an added value?

**Comment by rtritto** [comment]
> Does it bring an added value?

This is a draft.

I did some changes, can you review and continue?

**Comment by brillout** [comment]
👍 

Seems like pnpm has a bug with Node.js 20?

**Comment by rtritto** [comment]
Yes, it's fixed in v8.3.1 ([source](https://github.com/pnpm/pnpm/issues/6424#issuecomment-1514649084))

**Comment by rtritto** [comment]
Seem that _pnpm v8_ only removes Node.js v14 (source: https://github.com/pnpm/pnpm/releases/tag/v8.0.0).
Lockfile needs to be regenerated.
Should we use this PR?

**Comment by brillout** [comment]
> Should we use this PR?

Ok 👍

**Comment by rtritto** [comment]
Related error: https://github.com/cacjs/cac/issues/143

**Comment by rtritto** [comment]
> Related error: [cacjs/cac#143](https://github.com/cacjs/cac/issues/143)

Fixed with https://github.com/brillout/vite-plugin-ssr/pull/842/commits/099e56ea2d2dd0bf48c8f56edfad6be17e2181af

**Comment by rtritto** [comment]
Current version of _pnpm_ seems that install exact version instead of the minor one 👀

Fix of lockfile:
- https://github.com/brillout/vite-plugin-ssr/pull/842/commits/099e56ea2d2dd0bf48c8f56edfad6be17e2181af
- https://github.com/brillout/vite-plugin-ssr/pull/842/commits/958dfbbab47a01ce40ddd9548f7162b67232e9a0

**Comment by brillout** [comment]
Seems like the workaround is to set `resolution-mode=highest`?

**Comment by rtritto** [comment]
I added `resolution-mode=highest` in `~/.npmrc` and `~/vite-plugin-ssr/.npmrc` and I regenerated .
It doesn't work (no changes in _lockfile_).
e.g.:
```js
    es-module-lexer:
      specifier: ^0.10.0
      version: 0.10.0    // wrong: latest of v0 is 0.10.5
    esbuild:
      specifier: ^0.17.0
      version: 0.17.0    // wrong: latest is 0.17.18
    fast-glob:
      specifier: ^3.0.0
      version: 3.0.0    // wrong: latest is 3.2.12
```
Maybe the problem is related to workspace.

**Comment by brillout** [comment]
I think you have to remove the lock file before: `$ rm pnpm-lock.yaml && pnpm install`.

**Comment by rtritto** [comment]
> I think you have to remove the lock file before: `$ rm pnpm-lock.yaml && pnpm install`.

I always removed it before install.

**Comment by brillout** [comment]
If you want we can close an re-open later once pnpm's discussion about its new resolution strategy settles down?

**Comment by brillout** [comment]
I made some minor changes: https://github.com/brillout/vite-plugin-ssr/pull/842/commits/ffaa24e0bcde423f52912da5ad0b84bdfadac28a.

**Comment by rtritto** [comment]
> If you want we can close an re-open later once [pnpm's discussion about its new resolution strategy](https://github.com/pnpm/pnpm/issues/6463) settles down?

If nothing changes, I would leave opened because it's visible to further comments from community

**Comment by rtritto** [comment]
I suggest to set manually the minor version copying from previous lockfile (same `^` or exact version)
By this way, we safe know what are minor versions where the project starts to work

**Comment by brillout** [comment]
👍 I think that should work yes.

Once the PR is green we can think about what semver/resolution strategy we want to choose.

**Comment by rtritto** [comment]
> Anyway I suggest to set manually the minor version copying from previous lockfile (same ^ or exact version)
By this way, we safe know what are minor versions where the project starts to work

Done in https://github.com/brillout/vite-plugin-ssr/pull/842/commits/acad008cff7f8953fb511bfcc1eff8b3aec6acf9

Please can you remove/replace checks of Node v14?

**Comment by brillout** [comment]
👍 We can create `win16` and replace `win14` with it.

**Comment by rtritto** [comment]
Dependencies of _telefunc_ are outdated:

[/telefunc-v1/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/examples/telefunc-v1/package.json)
```json
    "typescript": "^5.0.4",
    "vite": "^4.2.2",
```

[/telefunc/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/examples/telefunc/package.json)
```json
    "typescript": "^4.8.4",
    "vite": "^3.0.9"
```

**Comment by rtritto** [comment]
[CI / Boilerplates - Ubuntu - Node.js 20](https://github.com/brillout/vite-plugin-ssr/actions/runs/4895748101/jobs/8741723573?pr=842)
Issue: https://github.com/TypeStrong/ts-node/issues/1997

**Comment by brillout** [comment]
Indeed, the only blocker left is https://github.com/TypeStrong/ts-node/issues/1997.

**Comment by rtritto** [comment]
> > In [63ed71f](https://github.com/brillout/vite-plugin-ssr/commit/63ed71f42f9d6d57665cf8b5a1090ff4c07c4259) I locked the esbuil version to 0.17.10 (we are sure that this version works).
> 
> I think it's safe to install _esbuild_ v0.17.18 (esbuild@^0.17.18) due to same errors of CIs.

Should we update _esbuild_ to v0.17.18 (esbuild@^0.17.18)?

**Comment by rtritto** [comment]
I think that we should update _@types/node_ to v20 in:
- [/boilerplates/boilerplate-react-ts/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/boilerplates/boilerplate-react-ts/package.json)
- [/boilerplates/boilerplate-vue-ts/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/boilerplates/boilerplate-vue-ts/package.json)
- [/docs/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/docs/package.json)
- [/examples/path-aliases-v1/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/examples/path-aliases-v1/package.json)
- [/examples/path-aliases/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/examples/path-aliases/package.json)
- [/examples/react-full-v1/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/examples/react-full-v1/package.json)
- [/examples/react-full/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/examples/react-full/package.json)
- [/examples/vue-full-v1/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/examples/vue-full-v1/package.json)
- [/examples/vue-full/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/examples/vue-full/package.json)
- [/test/pageFlesSrc/package.json](https://github.com/brillout/vite-plugin-ssr/blob/main/test/pageFlesSrc/package.json)

**Comment by brillout** [comment]
> I think that we should update _@types/node_ to v20 in:

While the VPS repository uses Node.js 20 we can't and shouldn't assume the user to use Node.js 20.

> Should we update esbuild to v0.17.18 (esbuild@^0.17.18)?

Since Vite is a peer dependency, I'd suggest we take over Vite's dependency semvers.

**Comment by brillout** [comment]
Thanks for the PR 💚.

**Pull request merged**
