### PR TITLE
Vue Pinia Example w/ client routing

### PR DESCRIPTION
**Pull request by 4350pChris**

### CODE REVIEW

**Comment by 4350pChris** [comment]
Re-opened the PR incorporating the fix for the hydration mismatch.

**Comment by brillout** [comment]
See my latest commits. The test fixing one will explain to you why it works.

**Comment by brillout** [comment]
Alright, we are ready to merge. Let me know if you agree and I'll merge.

**Comment by 4350pChris** [comment]
Sure go ahead.

**Pull request merged**
